"""
discode_sdof_sim.py
===================

DISCODE on a **simulated single-DOF** system.  This is the demo script: pick a
system from the local library, the states are generated by integrating the
known equation, and the search has to rediscover it.

Because the data comes from an integrator, ``a = dv/dt`` and ``v = dq/dt`` hold
exactly, the work-energy identity closes, and the reward ceiling is ~1.0.  So
the only question this script asks is whether the pipeline can find the
equation — there is no data-quality confound.  That makes it the right place to
sanity-check any change to :mod:`discode_core` before touching real data.

Everything is N-DOF underneath; a single DOF is just ``n_dof == 1``, so this
runs the same :func:`discode_train.DISCODE_TRAIN` loop as the MDOF drivers.

Add a system by writing one ``TruthSystem`` and registering it in ``_REGISTRY``.

Grammar note for ``truth_taus``
-------------------------------
State layout is ``x1 = q``, ``x2 = qdot``.  Every variable leaf carries an
implicit fitted coefficient, so ``['add', 'x1', 'x2', 'end']`` is
``c1*q + c2*qdot`` — the whole linear oscillator.  Powers come from
``intpower`` (coefficient + integer exponent), so ``q^3`` is
``['intpower', 'x1']``.  Supplying a tau is optional; it only enables the
``[truth]`` reward printout, which tells you the score the search is aiming at.
"""

from __future__ import annotations

from discode_data import TruthSystem, build_truth_system, print_truth_rewards
from discode_train import DISCODE_TRAIN


# ── 1-DOF system library ────────────────────────────────────────────────────
def _duffing():
    """Damped Duffing oscillator:  qddot = -c*qdot - k*q - a*q^3."""
    c, k, a = 0.30, 1.0, 0.50

    def a0(s):
        return -c * s[1] - k * s[0] - a * s[0] ** 3

    return TruthSystem(
        name='sdof_duffing',
        accel_fns=[a0],
        truth_strs=[f"xddot = -{c:.4g}*xdot - {k:.4g}*x - {a:.4g}*x^3"],
        truth_taus=[['add', 'x1', 'x2', 'intpower', 'x1', 'end']],
        var_names=['x'],
        t_end=20.0, n_pts=2000, n_traj=4,
        ic_scale=[1.5, 1.5],       # [q, qdot]
        seed=0,
    )


def _linear():
    """Linear damped oscillator:  qddot = -c*qdot - k*q."""
    c, k = 0.20, 4.0

    def a0(s):
        return -c * s[1] - k * s[0]

    return TruthSystem(
        name='sdof_linear',
        accel_fns=[a0],
        truth_strs=[f"xddot = -{c:.4g}*xdot - {k:.4g}*x"],
        truth_taus=[['add', 'x1', 'x2', 'end']],
        var_names=['x'],
        t_end=15.0, n_pts=1500, n_traj=4,
        ic_scale=[1.0, 1.0],
        seed=0,
    )


def _vanderpol():
    """Van der Pol oscillator:  qddot = mu*(1-q^2)*qdot - q.

    Note this one is self-excited, not a free decay: trajectories converge onto
    a limit cycle rather than to rest.
    """
    mu = 0.60

    def a0(s):
        return mu * (1.0 - s[0] ** 2) * s[1] - s[0]

    return TruthSystem(
        name='sdof_vanderpol',
        accel_fns=[a0],
        truth_strs=[f"xddot = {mu:.4g}*(1-x^2)*xdot - x"],
        # mu*xdot - mu*x^2*xdot - x  ->  c1*x + c2*xdot + c3*(x^2 * xdot)
        truth_taus=[['add', 'x1', 'x2', 'mul', 'intpower', 'x1', 'x2',
                     'end', 'end']],
        var_names=['x'],
        t_end=20.0, n_pts=2000, n_traj=4,
        ic_scale=[2.0, 2.0],
        seed=0,
    )


_REGISTRY = {
    'duffing':   _duffing,
    'linear':    _linear,
    'vanderpol': _vanderpol,
}


def get_sdof_system(key):
    if key not in _REGISTRY:
        raise ValueError(f"Unknown SDOF system '{key}'. "
                         f"Choose from {sorted(_REGISTRY)}.")
    return _REGISTRY[key]()


# ── Entry point ─────────────────────────────────────────────────────────────
def DISCODE_SDOF_SIM(
    system_key       = 'duffing',
    # data generation
    n_traj           = None,     # None = use the spec's value
    t_end            = None,
    n_pts            = None,
    seed             = None,
    plot_data        = False,
    show_truth       = True,     # print the reward of the known structure
    # search
    n_epochs         = 300,
    batch_size       = 200,
    max_len          = 20,
    lr               = 1e-4,
    alpha            = 0.20,
    C                = 5,
    G                = 5,
    lam_start        = 0.02,
    lam_end          = 0.001,
    eps              = 0.2,
    beta             = 0.01,
    max_buffer       = 500,
    beam_interval    = 10,
    beam_width       = 20,
    novelty_weight   = 0.15,
    energy_normalize = True,
    max_traj         = None,
    w_acc            = 0.5,
    use_pool         = True,
    # policy architecture (see DISCODE_TRAIN)
    architecture          = 'joint',
    cross_slice_attention = True,
    n_layers              = 4,
    d_model               = 128,
    slice_order           = 'random',
    sample_order          = 'reward',
    seed_policy           = None,
):
    """Generate a 1-DOF system from the library and try to rediscover it."""
    spec = get_sdof_system(system_key)
    system = build_truth_system(spec, n_traj=n_traj, t_end=t_end,
                                n_pts=n_pts, seed=seed)

    if plot_data:
        from discode_data import plot_system_data
        plot_system_data(system)

    if show_truth:
        print_truth_rewards(system, max_traj=max_traj, w_acc=w_acc,
                            energy_normalize=energy_normalize)

    return DISCODE_TRAIN(
        system_data      = system,
        n_epochs         = n_epochs,
        batch_size       = batch_size,
        max_len          = max_len,
        lr               = lr,
        alpha            = alpha,
        C                = C,
        G                = G,
        lam_start        = lam_start,
        lam_end          = lam_end,
        eps              = eps,
        beta             = beta,
        max_buffer       = max_buffer,
        beam_interval    = beam_interval,
        beam_width       = beam_width,
        novelty_weight   = novelty_weight,
        energy_normalize = energy_normalize,
        max_traj         = max_traj,
        w_acc            = w_acc,
        use_pool         = use_pool,
        architecture          = architecture,
        cross_slice_attention = cross_slice_attention,
        n_layers              = n_layers,
        d_model               = d_model,
        slice_order           = slice_order,
        sample_order          = sample_order,
        seed                  = seed_policy,
    )


if __name__ == '__main__':
    DISCODE_SDOF_SIM(
        system_key = 'duffing',
        n_epochs   = 300,
        batch_size = 200,
        max_len    = 20,
        plot_data  = True,
    )
